### ISSUE TITLE
[Etapa 02] - Metodologia

### ISSUE THREAD

**Issue by alicecomoura** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e1-proj-web-t12-dynamic-ead#43]
A metodologia adotada pelo time foi o SCRUM.

**Comment by shigerysasaki** [comment]
#### Etapa 02
#### 1) Metodologia

- 1.1 Planejamento: Foi feita uma reunião com o professor na quarta-feira dia 05/04/2023 para ser definido a metodologia utilizada junto aos grupos.
 
- 1.2 Execução: Foi aprezentado a metodologia Scrum, suas funçoes e qual membro do grupo ficaria responsavel por cada parte, bem como foi apresnetado o kamban como forma de distribiução de afaseres.
- 1.3 Evidências: 

![Evidencia de discord](img/discord.png)
![Evidencia de metodologia](img/metodologia.png)
![Evidência de Kanman](img/kanban.png)
